config/routes.rb
WordjackTest::Application.routes.draw do
  resources :users, controller: "registrations", only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :contacts

  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

  get "statics/get_stuff"

  root :to => 'statics#home'

end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Contact < ActiveRecord::Base
  attr_accessible :name

  belongs_to :user

  validates :name, presence: true, length: { maximum: 40 }
  validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :contacts, dependent: :destroy

  validates :name, presence: true, length: { maximum: 40 }
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true, format: { with: valid_email_regex }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6}

  has_secure_password
  before_save :create_remember_token

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :logged_in_user
  before_filter :correct_authorized_user, except: [:new, :create]

  def new
    @contact = Contact.new
  end

  def index
    @contacts = current_user.contacts
  end

  def show
    @contact  = Contact.find(params[:id])
  end

  def edit
    @contact  = Contact.find(params[:id])
  end

  def create
    @contact = current_user.contacts.build(params[:contact])
    if @contact.save
      flash[:success] = "You have created a new contact!"
      redirect_to contacts_url
    else
      flash.now[:error] = "Contact creation has failed"
      render 'new'
    end
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(params[:contact])
      flash[:success] = "You have successfully updated your contact!"
      redirect_to(@contact)
    else
      flash.now[:error] = "Contact update has failed"
      render 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to contacts_url
  end

  #After the user is authorized he will be redirected to his intended destination, or go to the home page
  def correct_authorized_user
    @contacts = current_user.contacts
    if(@contacts.blank?)
      flash[:notice] = "Please create a new contact!"
      redirect_to_target new_contact_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @registrant = User.new
  end

  def create
    @registrant = User.new(params[:user])
    if @registrant.save
      login @registrant
      flash[:success] = "You have created a new registrant!"
      redirect_to root_url
    else
      render 'new'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      login user
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid Login - You will be sent to the homepage momentarily'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end

  def logged_in?
    !current_user.nil?
  end
  
  def logout
    current_user = nil
    cookies.delete(:remember_token)
  end

  def logged_in_user
		unless logged_in?
			store_location
			redirect_to login_path, notice: "Please log in."
		end
  end

  #Store the user's intended path
  def store_location
    session[:return_to] = request.fullpath
  end

  #redirect the user to his intended target after authorization, or go to the default_path if session[:return_to] is nil
  def redirect_to_target(default_path)
    redirect_to(session[:return_to] || default_path)
    clear_target_path
  end

  private

  def user_from_remember_token
    remember_token = cookies[:remember_token]
    User.find_by_remember_token(remember_token) unless remember_token.nil?
  end

  #Delete the cookie that holds the user's intended path
  def clear_target_path
    session.delete(:return_to)
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/contacts/_form.html.haml
%br/
=form_for @contact do |f|
  =render 'shared/error_messages', :target => @contact
  %div{class: "block_middle table_display"}
    %div{:class=>"table_row"}
      %span{:class=>"text_right table_cell"}
        =f.label :name
      %span{:class=>"text_left table_cell"}
        =f.text_field :name
    %div{:class=>"table_row"}
      %span{:class=>"text_right table_cell"}
      %span{:class=>"text_left table_cell"}
        =f.submit(button_name, {id: "submit_contact"})
    %br/

app/views/contacts/edit.html.haml
%title Edit Your Contact

%div{id: "edit_contact_form"}
  %h1{id: "page_header", class: "text_middle" } New Contact Form
  %span{id: "close_edit_contact", class: "close_element", title: "Click to return to the contacts page"}
  =render(partial: "form", :locals=>{button_name: "Update"})

:javascript
  $(document).ready(function() {
    //Show the translucent_background div for the lightbox effect.
    $('#translucent_background').show();
    $('div#edit_contact_form').css({'background-color' : '#eee'});

    $('#close_edit_contact').click(function(){ location.href="#{contacts_path}" })
  });

app/views/contacts/index.html.haml
%title Your Contacts Page

%table{id: "contacts_table", class: "block_middle"}
  %caption
    Contacts List
  %tr
    %th{class: "left_round"}
      Names
    %th
    %th{class: "right_round"}
  -@contacts.each do |contact|
    %tr
      %td{class: "contact_cell"}
        =contact.name
      %td{class: "text_middle"}
        = link_to("edit", edit_contact_path(contact), class: "edit_link")
      %td{class: "text_middle"}
        = link_to "delete", contact, method: :delete, confirm: "Do you really want to delete this contact?", class: "delete_link"

app/views/contacts/new.html.haml
%title Create Your New Contact

%div{id: "new_contact_form"}
  %h1{id: "page_header", class: "text_middle" } New Contact Form
  %span{id: "close_new_contact", class: "close_element", title: "Click to return to the homepage"}
  =render(partial: "form", :locals=>{button_name: "Create"})

:javascript
  $(document).ready(function() {
    //Show the translucent_background div for the lightbox effect.
    $('#translucent_background').show();
    $('div#new_contact_form').css({'background-color' : '#eee'});

    $('#close_new_contact').click(function(){ location.href="#{root_path}" })
  });

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag    "menu"
    = javascript_include_tag "application"
    = javascript_include_tag "menu"
    = csrf_meta_tags
  %body{id: "main", class: "block_middle"}
    %header{id: "main_header"}
      %nav
        %div{id: "menu"}
          %ul{class: "menu"}
            %li
              %a{href: "#{root_path}", class: "parent"}
                %span Home
            -unless(logged_in?)
              %li
                %a{href: "#{new_user_path}", class: "parent"}
                  %span Registration
            -if(logged_in?)
              %li{class: "last"}
                %a{href: "#{contacts_path}", class: "parent"}
                  %span Contacts
                %ul{class: "above_flash_notice"}
                  %li
                    %a{href: "#{new_contact_path}"}
                      %span Add a New Contact
                  %li
                    %a{href: "#{contacts_path}"}
                      %span Show All Your Contacts
        %div{id: "user_authentication"}
          -if(logged_in?)
            You are logged in as
            %span{class: 'bold_text'}
              = @current_user.name
            |
            = link_to("Logout", logout_path, class: "login_link red_text")
          -else
            = link_to("Login", login_path, class: "login_link green_text")
      -flash.each do |key, value|
        =content_tag(:div, value, :class => "flash_#{key}")
    %section
      %article{:id=>"main_content"}
        = yield
    %div{id: 'translucent_background'}

app/views/shared/_error_messages.html.haml
-if target.errors.any?
  %div{id: "error_explanation"}
    %h2
      =pluralize(target.errors.count, "error")
      prohibited this
      =target.class.to_s.underscore.humanize.downcase
      from being saved:
    %p
      There were problems with the following fields:
    %ul
      -target.errors.full_messages.each do |msg|
        %li
          =msg

app/views/statics/home.html.haml
%title
  Daddies Home Page
%h1{id: "page_header", class: "text_middle" } Home Page
%br/
%div{id: "home_description"}
  This application allows users to register, log in and manage a list of contacts.